//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Nov  9 2017 20:17:28).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIKit.h>

@class NSAttributedString, NSLayoutConstraint, NSManagedObjectID, NSString, UILabel, UIPanGestureRecognizer, UISelectionFeedbackGenerator, UIView, WABadgedLabel, WALabel, WAProfilePictureThumbnailView, _WAChatSessionCellIndicatorsView, _WAChatSessionCellSideButtonsView;
@protocol WAChatSessionCellDelegate;

__attribute__((visibility("hidden")))
@interface WAChatSessionCell : UITableViewCell
{
   
    NSString *_jid;
   
    UIView *_containerView;
    WABadgedLabel *_nameLabel;
    UILabel *_senderLabel;
    UILabel *_timeLabel;
//
//    _WAChatSessionCellSideButtonsView *_rightSideButtonsView;
//    _WAChatSessionCellSideButtonsView *_leftSideButtonsView;
  
    WALabel *_messageLabel;
    UILabel *_activityLabel;
    WAProfilePictureThumbnailView *_imageViewContactPicture;
   
}

//+ (id)messageTypeStringForMessage:(id)arg1;
//+ (id)messageStatusStringForMessage:(id)arg1;
//+ (id)buttonInView:(id)arg1;
//+ (double)preferredHeight;
//+ (id)cellWithReuseIdentifier:(id)arg1;
//+ (id)textFormatter;
//+ (void)initialize;
@property(retain, nonatomic) NSManagedObjectID *messageIDForAccessibilityLabel; // @synthesize messageIDForAccessibilityLabel=_messageIDForAccessibilityLabel;
@property(copy, nonatomic) NSString *chatActivityText; // @synthesize chatActivityText=_chatActivityText;
//@property(copy, nonatomic) NSAttributedString *messageText; // @synthesize messageText=_messageText;
//@property(nonatomic) _Bool showGroupParticipants; // @synthesize showGroupParticipants=_showGroupParticipants;
//@property(nonatomic) _Bool didPinButtonAdded; // @synthesize didPinButtonAdded=_didPinButtonAdded;
//@property(nonatomic) _Bool messageTextMarkupEnabled; // @synthesize messageTextMarkupEnabled=_messageTextMarkupEnabled;
//@property(nonatomic) _Bool isLayoutRTL; // @synthesize isLayoutRTL=_isLayoutRTL;
//@property(nonatomic) _Bool unknownContact; // @synthesize unknownContact=_unknownContact;
//@property(retain, nonatomic) WAProfilePictureThumbnailView *imageViewContactPicture; // @synthesize imageViewContactPicture=_imageViewContactPicture;
@property(retain, nonatomic) UILabel *activityLabel; // @synthesize activityLabel=_activityLabel;
@property(retain, nonatomic) WALabel *messageLabel; // @synthesize messageLabel=_messageLabel;
// @synthesize containerViewRightToContentViewConstraint=_containerViewRightToContentViewConstraint;

@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) UILabel *senderLabel; // @synthesize senderLabel=_senderLabel;
@property(retain, nonatomic) WABadgedLabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(nonatomic) __weak id <WAChatSessionCellDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool shouldAnimatePinAction; // @synthesize shouldAnimatePinAction=_shouldAnimatePinAction;
@property(nonatomic) _Bool ignoreExternalUpdates; // @synthesize ignoreExternalUpdates=_ignoreExternalUpdates;
//@property(nonatomic) long long unreadCount; // @synthesize unreadCount=_unreadCount;
//@property(nonatomic) _Bool archived; // @synthesize archived=_archived;
//@property(nonatomic) _Bool muted; // @synthesize muted=_muted;
//@property(nonatomic) _Bool pinned; // @synthesize pinned=_pinned;
@property(copy, nonatomic) NSString *jid; // @synthesize jid=_jid;

//- (void)xmppConnectionChatStateDidChange:(id)arg1;
//- (void)reloadTimestampLabelTextColor;
//- (void)reloadFonts;
//- (void)reloadMessageSnippetWithMessage:(id)arg1;
//- (void)configureWithChatSession:(id)arg1 message:(id)arg2 listFirst:(id)arg3 showPinButton:(_Bool)arg4 showVerifiedName:(_Bool)arg5 startPinAnimation:(_Bool)arg6;
//- (void)configureWithChatSession:(id)arg1 message:(id)arg2 showPinButton:(_Bool)arg3 showVerifiedName:(_Bool)arg4 startPinAnimation:(_Bool)arg5;
//- (void)configureForGroupsInCommonTableWithChatSession:(id)arg1 listFirst:(id)arg2;
//- (id)accessibilityCustomActions;
//- (id)accessibilityValue;
//- (id)accessibilityLabel;
//- (unsigned long long)accessibilityTraits;
//- (_Bool)isAccessibilityElement;
//@property(readonly, nonatomic, getter=isDisplayingSideButtons) _Bool displayingSideButtons;
//@property(readonly, nonatomic, getter=isResizingSideButtons) _Bool resizingSideButtons;
//- (void)setChatActivityText:(id)arg1 animated:(_Bool)arg2;
//- (void)startPinAnimation;
//- (void)pinAction:(id)arg1;
//- (void)markUnreadAction:(id)arg1;
- (void)archiveAction:(id)arg1;
//- (void)showMoreOptions:(id)arg1;
//- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
//- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
//- (void)hideSideButtonsAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)cancelResizingSideButtons;
- (void)endSwipeWithGestureRecognizerState:(long long)arg1;
- (void)expandOrCollapseSideButtonsIfNecesary:(_Bool)arg1;
- (void)expandOrCollapseLeftSideButtonsIfNecessary;
- (void)handleCellSideSwipe:(id)arg1;
- (void)endedChangingSideButtons;
- (void)beganChangingSideButtons;
- (void)updateContentViewHorizontalPosition;
- (void)reloadTitleOfMarkUnreadButton;
- (id)accessoryButton;
- (void)safeAreaInsetsDidChange;
- (void)updateLeadingContentMargin;
- (void)layoutMarginsDidChange;
- (void)updateSeparatorInset;
//- (void)willTransitionToState:(unsigned long long)arg1;
- (void)tintColorDidChange;
- (void)layoutSubviews;
//- (void)setHighlighted:(_Bool)arg1 animated:(_Bool)arg2;
//- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
//- (void)prepareForReuse;
//- (void)addAutolayoutConstraints;
//- (void)dealloc;
//- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

